### PR TITLE
master

### PR DESCRIPTION
**Pull request by IgorGanapolsky**
Update gradle version and android library versions.

### CODE REVIEW

**Comment by h6ah4i** [comment]
Hi. Thanks for the PR. I have just checked it, here's my conclusion;

- merge into the `master` branch
 - :point_right: This project is actively developed on the `develop` branch, so some of the changes are already done in that branch. I will pick some relevant fixes and merge them manually.

- `com.android.tools.build:gradle:1.3.1`, `buildToolsVersion '23.0.1'`
  - :point_right: Thanks, I will update these statements

- `compileSdkVersion 23`, support libraries v23.0.1
 - :point_right: Already have done.

- Remove unused `material_shadow_z*.9.xml` files
 - :point_right: I don't want to remove them because they can help the users of this library how to tweak the visuals of the item shadows

- Bump to gradle 2.7
 - :point_right: Thanks I will update this, but `gradle-wrapper.jar` should also be regenerated with using Gradle 2.7.

**Comment by IgorGanapolsky** [comment]
Who says I removed material_shadow files?  I just renamed them so that they
comply with Android Studio rules.  Otherwise, the build was failing
compilation due to illegal name!

**Comment by h6ah4i** [comment]
Your commit message says "renamed", but actually no new named files are added though.

**Comment by h6ah4i** [comment]
This PR has been merged as #117 with some modifications;

- *Rename* `material_shadow_z1.*.xml` files (to avoid build error with the Android build tools plugin v1.3.1)
- Also updates gradrew wrapper script

Thanks!

**Pull request closed without merging**
