### PR TITLE
fixed crash during dragging items and device rotation

### PR DESCRIPTION
**Pull request by polyak01**

### CODE REVIEW

**Comment by h6ah4i** [comment]
@polyak01 Hi, thanks for the contribution!

When I saw your code, I thought that it looked like a weird fix, so there must be a different fault causing the issue. I checked another lines of my code carefully and then I found them!

### The culprit

I use `removeCallbacks(null)` in the `InternalHandler.release()` method, but it should be **`removeCallbacksAndMessages(null)`**.

### Asks

Please fix the issue in correct way and update this PR 🙇 

1. Revert the line `2222` change
2. Change `removeCallbacks(null)` to `removeCallbacksAndMessages(null)`
  **IMPORTANT** The same fault exists in the `RecyclerViewSwipeManager`, fix this too.
3. Confirm that the problem has been resolved.
4. Change the base branch of this PR to `develop`

**Comment by polyak01** [comment]
https://github.com/h6ah4i/android-advancedrecyclerview/pull/362

**Comment by h6ah4i** [comment]
PR #362 has been merged now.

**Comment by polyak01** [comment]
@h6ah4i I would like to import the library into the project with most of the new fixes. When I can do it?)

**Comment by h6ah4i** [comment]
@polyak01 I'm now prepareing the next version (`v0.10.4`) release. Just a moment...

**Comment by polyak01** [comment]
@h6ah4i Thanks!)

**Comment by h6ah4i** [comment]
@polyak01 I have just finished releasing [`v0.10.4`](https://bintray.com/h6ah4i/maven/android-advancedrecyclerview/0.10.4) 🎉

**Pull request closed without merging**
