### PR TITLE
Feature : API to set longpress timeout for drag drop

### PR DESCRIPTION
**Pull request by vinayak-garg**
I have added an API to set longpress timeout for drag drop. 

The default timeout (500ms) is somewhat low. While scrolling through a long grid layout, I end up dragging some item accidentally. 

By adding API, user can increase the timeout to some greater value. Also user can adapt timeout based on number of items.

For example I used a timeout of 750 to eliminate accidental drag, while retaining the experience of long press.

Please review.

### CODE REVIEW

**Comment by h6ah4i** [comment]
Hi. Thanks for the PR.

I checked your modification and I noticed an issue. The timeout value (`mLongPressTimeout`) is only applied when creating an instance of the `InternalHandler` class, so calling the `setLongPressTimeout()` method after the `attachRecyclerView()` method will not work. You should pass the time out value on every `
InternalHandler.startLongPressDetection()` call instead.

Thanks ;)

**Comment by vinayak-garg** [comment]
Hi, thanks for the review and catching the issue.

If you are going to take PR #125, then I can close this PR. As that seems a better fix for the main issue. But I am yet to test it.

**Comment by h6ah4i** [comment]
Hi. I have included this PR (with the fix I mentioned) in #127 because the `setLongPressTimeout()` method is useful for someone else.

**Comment by h6ah4i** [comment]
This PR is included in #127.

**Pull request closed without merging**
